### PR TITLE
Display subscription picker on check in and check out

### PR DESCRIPTION
**Pull request by ernbrn**
- Show that the account has no subscriptions
- In the future, there will be the option to upgrade the subscription in this place

**Before Merging**
I need to add subscriptions to my account on staging to verify it works

### CODE REVIEW

**Comment by cndreisbach** [comment]
@ernbrn You mention you need to do something before merging -- can you let me know when this is ready to merge?

**Comment by ernbrn** [comment]
@cndreisbach I just need some subscriptions on the staging server so I can verify my code works. Could you manually add some for me or give me instructions as to how? I couldn't figure out how to since the subscription payment stuff was ripped out.

**Comment by cndreisbach** [comment]
@ernbrn I've added some for you.

**Comment by ernbrn** [comment]
@cndreisbach Still getting a 403 when trying to hit the tag endpoint, but I feel confident my request is fine. This should be good to merge!

**Comment by cndreisbach** [comment]
Ok! I'll take a look at the endpoint.

**Pull request merged**
