### PR TITLE
Hookup map view to api

### PR DESCRIPTION
**Pull request by damianhouse**
Added map markers feature to the map. I have code to use little togo boxes instead of the markers but I don't think they are as clear without a little stick on the bottom like a marker.

### CODE REVIEW

**Comment by cndreisbach** [comment]
This looks good, but I have one question: `node_modules/.yarn-integrity` seems like it shouldn't be committed. Can you check out what's up with that?

**Comment by damianhouse** [comment]
@cndreisbach Awesome. I researched that .yarn-integrity file and apparently it happens sometimes when you run yarn for React. removed the React node modules folder and I ran yarn again the file went away. I also resolved the merge conflict from master and pushed.

**Comment by damianhouse** [comment]
@cndreisbach Currently on the mobile app i'm getting an array of locations with this data `{
    "address": "2510 University Dr, Durham, NC 27707, USA",
    "latitude": 35.974581,
    "longitude": -78.9244479,
    "name": "Q-Shack",
    "phase": 1,
  }`
As a feature request it would be nice to receive whether or not it's an 'In' location, 'Out' location or an 'InOut' location and we could drop different pins depending on that and maybe have a little map legend with what each means. Currently we are just dropping a pin on locations.

**Comment by cndreisbach** [comment]
What you're receiving is participating restaurants, not checkin/checkout
locations. I know that's a little confusing, as each participating
restaurant is a checkout location. I'll think about how to unify that.

**Pull request merged**
